project:
  type: website
  resources:
    - "lectures/L*.qmd"

website:
  title: "course-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - learning.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true





